#!/bin/sh

ulimit -n 2560
ulimit -c unlimited
./magic_Linux32 /r ./ /e /gs/pack_data/lib_gs32.pak/gs/start_gs.o /b /gs/pack_data/lib_gs32.pak -m gs/gsmem.cfg /D _RELEASE /D CONFIG=gs/gs.ini /D AUTH= /D AUTH_MD5=767E51FE9E9A2F1EB5E689D74AA02426 /D INIT_SOCKET_SCANNER_TEMP /D TRADITIONAL --enable-socket-daemon 0 --stack-size 1024
